// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TerraSenseApi.Data;

#nullable disable

namespace TerraSenseApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TerraSenseApi.Models.ObservacaoRelatorio", b =>
                {
                    b.Property<int>("IdObservacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OBSERVACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObservacao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<int>("RelatorioPlantacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RELATORIO");

                    b.HasKey("IdObservacao");

                    b.HasIndex("RelatorioPlantacaoId");

                    b.ToTable("TB_OBSERVACAO_RELATORIO");
                });

            modelBuilder.Entity("TerraSenseApi.Models.RelatorioPlantacao", b =>
                {
                    b.Property<int>("IdRelatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RELATORIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRelatorio"));

                    b.Property<decimal>("Chuva")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataRelatorio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdPlantacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PLANTACAO");

                    b.Property<decimal>("Ndvi")
                        .HasPrecision(4, 2)
                        .HasColumnType("DECIMAL(4,2)");

                    b.Property<string>("NomePlantacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomePropriedade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("RadiacaoSolar")
                        .HasPrecision(8, 2)
                        .HasColumnType("DECIMAL(8,2)");

                    b.Property<string>("StatusGeral")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Temperatura")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("Umidade")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("IdRelatorio");

                    b.ToTable("TB_RELATORIO_PLANTACAO");
                });

            modelBuilder.Entity("TerraSenseApi.Models.ObservacaoRelatorio", b =>
                {
                    b.HasOne("TerraSenseApi.Models.RelatorioPlantacao", "RelatorioPlantacao")
                        .WithMany("Observacoes")
                        .HasForeignKey("RelatorioPlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatorioPlantacao");
                });

            modelBuilder.Entity("TerraSenseApi.Models.RelatorioPlantacao", b =>
                {
                    b.Navigation("Observacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
